addons:
  sonarcloud:
    organization: "mariorez"
    token:
      secure: "g+NABySaW3pJPCJUa36FhYMP7uUD8dZxnTOF4z5/OTmx82UDqF1PHDU4+y4aYvBv8t3a5wj9ujrYQoVtPrYcBlqq4wfiBy7pORZEAbzkoxNL1sE8bzQdNOFulaJmUCVCx+XGbvbDINOi7+BiqVu3QdAsEETXqxPTfLvwlXL75ZqtjuflaeZv76bglsLWIEg55lb+S+ZySFbZ70vwvbkfw4/87BhEB2cuGDcsZEp/ZPtvgqzKTFkEewK7cMhQb5Q+Eg1wRTSD2SH0aUc2H4C+FgtQoNMVAneT4Vk2AqohL9/DYAOedzdxVqR+tu86SelNKpXD0AuzVUduT8bfLG6JeJ2GCO/7dXRrv/kb1NF6DWWqHbhXR7lK48MMny4z3qicDr3DXI/4MavymcVDOKzMUlRq2DQ1HM3FKRnYOvnJHHzr6XjFBUHUzTS7ZwcnHxazhbnci4gFc3Yto1MdgJ8IMJOv+VwRBF7P0bt59ae/mrUb/0lJENcXGGlPGs9fnDb371TvH+N5IpfUrBN7ftL0Zv0YCgySHXH/NSljRMU8C2tl41R+QVFNOMTZ0X4x9tHo6gJgGLIXVNnrntBstCsHOpUOfMFxbiIE1o+vNbWQ9v23rtBp7IDp4oNEkHqQGE7LU0J1iDfpHHx9Wr3lLYgCW1jfaJqp04Y3gBOuvVDe0iM="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=mariorez_kanban-board